### ISSUE TITLE
デザイン修正

### ISSUE THREAD

**Issue by ueda1** [kotacky/yorimichi#20]
#### 修正内容
- label -> .label
- 画面サイズをiPhone 6/7/8 にした場合のドロワの大きさ -> ドロワ及びテキストサイズを相対的に表示する

#### 修正対象
- android.css
- iphone.css
- config.css

**Comment by Yutaka0123** [comment]
https://github.com/kotacky/yorimichi/pull/26
上記にて対応

**Comment by ueda1** [comment]
issueの解消を確認したのでクローズ
